### PR TITLE
Indirect notification icons in tray and tabs

### PR DESCRIPTION
**Pull request by FeikoJoosten**
Currently Ferdi doesn't differentiate between direct and indirect notification badges.

Note, this is pretty much a copy pasta from getferdi/ferdi#590, but with some extra functionality.

### Description

* All Platforms- Add an icon used for showing indirect notifications in the taskbar. This is just a copy of the notifications icon, but with a blue(#0088cc) color (like slack, google chat etd)
* All Platforms - Replace the red color used for indirect notifications in tabbed view for a service to
#0088cc (Blue) color

### Motivation and Context

This PR is to address [#583](getferdi/sponsors-only#1045)

### How Has This Been Tested?

* This has been tested on Windows 10 on a Ferdi dev environment.

### Screenshots (if appropriate):
Indirect and direct notification bubble in the side bar.
image
Indirect notification bubble on the tray icon.
image

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [X] My code follows the code style of this project (run `$ yarn lint`).

### CODE REVIEW

**Comment by FeikoJoosten** [comment]
Please note that my PR also addresses an issue where the original change in [src/styles/tabs.scss](https://github.com/Room4O4/ferdi/commit/bf917abb443b5820306b15944357e5fa33aa8d20#diff-d8192ba4a8e9b39d46928a4e315bf4a3) would override the color of the direct notification bubble as well. Which would turn all notifications to the blue color.

**Comment by sampathBlam** [comment]
@FeikoJoosten : Your changes look good to us. Can you resolve the conflict alone, so that we can proceed with merging this PR?

**Review by sampathBlam — CHANGES_REQUESTED** [review]
@FeikoJoosten : Your changes look good to us. Can you resolve the conflict regarding the taskbar.ico and push the changes, so that we can proceed with merging this PR?

**Comment by FeikoJoosten** [comment]
@sampathBlam the merge conflicts have been resolved. I resolved the conflict using my version of the .ico. As looking at the quality of them both, mine seemed more high res.

**Comment by sampathBlam** [comment]
@FeikoJoosten : Great ! Thank you

**Review by sampathBlam — APPROVED** [review]

**Pull request merged**
